import type { Metadata } from "next";
import "./globals.css";
import Header from "../app/components/Header"; 
import {Inter} from 'next/font/google'

const inter = Inter({ subsets: ['latin']})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* header */}
      <Header/>
        {children}
      </body>
    </html>
  );
}
